# Generated by Django 4.1.2 on 2022-10-18 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('isbn_number', models.IntegerField(max_length=15)),
                ('publication', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=243)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.book')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('fine_date', models.DateField()),
                ('fine_amount', models.IntegerField()),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.issuedbook')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.category'),
        ),
    ]
