# Generated by Django 4.1.2 on 2022-10-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_rename_user_student_user_id_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
