# Generated by Django 4.1.1 on 2022-12-12 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0008_alter_issuedbook_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 12, 14, 11, 646361)),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 12, 14, 11, 646346)),
        ),
    ]
