# Generated by Django 4.1.1 on 2022-12-22 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0018_alter_issuedbook_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 15, 10, 14, 379844)),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 15, 10, 14, 379829)),
        ),
    ]
