# Generated by Django 4.1.1 on 2022-12-22 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0019_alter_issuedbook_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 19, 56, 3, 991521)),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 19, 56, 3, 991504)),
        ),
    ]
